baseURL = "https://ayaen.xyz/"
languageCode = "en-us"
title = "Apfelstrudel"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  env = "development"
  description = "Writing as meandering as the mind that thought up apples in pastry"
  [params.label]
    text = "Apfelstrudel"
    fancy = "<span class='apfel-a'>A</span>pfelstrudel"
  defaultTheme = "dark"
  mainSections = ["posts"]
  disableThemeToggle = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowWordCount = false
  ShowAuthor = false
  ShowBreadCrumbs = false
  disableSpecial1stPost = true
  favicon = "favicon.ico"
  #customCSS = ["css/custom.css"]

  [params.homeInfoParams]
    Title = "Writing"
    Content = "Writing as meandering as the mind that thought up apples in pastry"

  [params.landingImageCredit]
    name = "Levart_Photographer"
    profile = "https://unsplash.com/@siva_photography"
    photo = "https://unsplash.com/photos/a-close-up-of-two-apples-on-a-table-WUd8XKFIotY"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
